port: 8000
gradio_share: false
logging_level: INFO

strategies:
  - name: Conservative
    label: Conservative
    description: Focus on stable and low-risk investments.
  - name: Balanced
    label: Balanced
    description: A mix of growth and stability.
  - name: Aggressive
    label: Aggressive
    description: High-risk, high-reward investments.

models:
  gemini:
    - name: gemini-2.0-flash
      label: Gemini
    # - name: gemini-2.0-pro # TODO Non funziona, ha un nome diverso
    #   label: Gemini Pro
  gpt:
    - name: gpt-4o
      label: OpenAIChat
  deepseek:
    - name: deepseek-chat
      label: DeepSeek
  mistral:
    - name: mistral-large-latest
      label: Mistral
  ollama:
    - name: gpt-oss:latest
      label: Ollama GPT
    - name: qwen3:8b
      label: Qwen 3 (8B)
    - name: qwen3:4b
      label: Qwen 3 (4B)
    - name: qwen3:1.7b
      label: Qwen 3 (1.7B)
    - name: qwen3:32b
      label: Qwen 3 (32B)
    - name: qwen3:14b
      label: Qwen 3 (14B)
    - name: phi4-mini:3.8b
      label: Phi 4 mini (3.8b)

api:
  retry_attempts: 3
  retry_delay_seconds: 2
  market_providers: [YFinanceWrapper, BinanceWrapper, CoinBaseWrapper, CryptoCompareWrapper]
  news_providers: [DuckDuckGoWrapper, GoogleNewsWrapper, NewsApiWrapper, CryptoPanicWrapper]
  social_providers: [RedditWrapper, XWrapper, ChanWrapper]

agents:
  strategy: Conservative
  team_model: qwen3:14b # the agents
  team_leader_model: gemini-2.0-flash # the team leader
  query_analyzer_model: qwen3:14b # query check
  report_generation_model: qwen3:32b # ex predictor
