services:
  app:
    build: .
    container_name: upo-app-ai
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      # Modelli supportati
      - OLLAMA_HOST=http://host.docker.internal:11434
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Chiavi per le crypto API
      - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
      - CDP_API_PRIVATE_KEY=${CDP_API_PRIVATE_KEY}
      - CRYPTOCOMPARE_API_KEY=${CRYPTOCOMPARE_API_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
