services:
  app:
    build: .
    container_name: upo-app-ai
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
